spring.application.name=genco2

# Cấu hình MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/evngenco2_khcncds}
spring.datasource.username=${DB_USER:evngenco2_khcncds}
spring.datasource.password=${DB_PASS:MatKhauSieuKho@2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tự động cập nhật cấu trúc bảng (chỉ dùng khi phát triển)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cấu hình Gửi Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranducmanh.dn@gmail.com
spring.mail.password=mxps jhxi wzai pmur
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true